### ISSUE TITLE
Set up Project with KanBan Board

### ISSUE THREAD

**Issue by rebaz36** [rebaz36/SpaceTravelers-React_Redux#25]
we've Set up the project with KanBan Board, and distributed the tasks. 
we also created milestones to ensure we stay on track with our progress
[Link to the Project](https://github.com/users/rebaz36/projects/3/views/1)

For this project, there are only two members on our team @rebaz36 & @ndorrh

**Comment by Davidosky007** [comment]
Hi @rebaz36 @ndorrh 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Card created properly 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rebaz36** [comment]
thanks for the review @Davidosky007
